Select * from RAWDATALOTUSNOTES where ShortName = 'HUZZ04DZ';

Delete From RAWDATALOTUSNOTES where RUNDATE = 20220323060009 AND NABSERIAL = '003DCQ744' AND SHORTNAME ='IN003DCQ';

Select * FROM RECONCILECONF where SYSTEM = 'IDPIN';

Select * From RAWDATALOTUSNOTES Where SERIALNUMBER = 'ZZ04DZ740';